### ISSUE TITLE
(CaseClauseError) no case clause matching:

### ISSUE THREAD

**Issue by Sotorin** [ueberauth/ueberauth_google#9]
I got all my IDs from the Google console, plugged them into the sample app and I got this error (it's at the very end). After I enabled the API things worked fine. I'm not sure if this is something that can be handled by the library itself (i.e. this case, when API is not turned on) or in the controller.

*\* (CaseClauseError) no case clause matching: {:ok, %OAuth2.Response{body: %{"error" => %{"code" => 403, "errors" => [%{"domain" => "usageLimits", "extendedHelp" => "https://console.developers.google.com/apis/api/plus/overview?project=889214574482", "message" => "Access Not Configured. Google+ API has not been used in project 889214574482 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=889214574482 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", "reason" => "accessNotConfigured"}], "message" => "Access Not Configured. Google+ API has not been used in project 889214574482 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=889214574482 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."}}, headers: [{"Vary", "X-Origin"}, {"Content-Type", "application/json; charset=UTF-8"}, {"Date", "Sat, 16 Apr 2016 23:07:47 GMT"}, {"Expires", "Sat, 16 Apr 2016 23:07:47 GMT"}, {"Cache-Control", "private, max-age=0"}, {"X-Content-Type-Options", "nosniff"}, {"X-Frame-Options", "SAMEORIGIN"}, {"X-XSS-Protection", "1; mode=block"}, {"Server", "GSE"}, {"Alternate-Protocol", "443:quic"}, {"Alt-Svc", "quic=\":443\"; ma=2592000; v=\"32,31,30,29,28,27,26,25\""}, {"Accept-Ranges", "none"}, {"Vary", "Origin,Accept-Encoding"}, {"Transfer-Encoding", "chunked"}], status_code: 403}}

**Comment by hassox** [comment]
@Sotorin I think we just need another clause on this case: https://github.com/ueberauth/ueberauth_google/blob/master/lib/ueberauth/strategy/google.ex#L118

to catch the 403 case. Would you be up for a PR?

**Comment by yordis** [comment]
@hassox I am having this issue with `ueberauth_twitter` as well

**Comment by Sotorin** [comment]
I'm elixir noob but I'll have some time next week and will take a look.
Perhaps I'll be able to contribute something.

**Comment by jochakovsky** [comment]
Hit this same issue when playing around with this strategy. Out of curiosity, is there a reason this is configured to use the Google+ API, which needs to be separately enabled? It seems like there are other options if you don't need to collect social networking information, but I'm totally new to all of this.

**Comment by doomspork** [comment]
Is there another option you recommend @jochakovsky?

**Comment by jochakovsky** [comment]
@doomspork I was able to figure out a possible alternative by playing around with this over the past few days. According to https://developers.google.com/identity/protocols/OpenIDConnect#obtaininguserprofileinformation, the two options for getting profile info are Google Sign-In and OpenID. Based on https://github.com/ueberauth/ueberauth_google/blob/master/lib/ueberauth/strategy/google.ex#L12, it seems like ueberauth_google is currently using the former.

I pulled ueberauth_example and switched over to the OpenID user profile method by changing that line to ``` @token_url "https://www.googleapis.com/oauth2/v3/userinfo"```. This endpoint is published by Google in their [OpenID discovery document](https://accounts.google.com/.well-known/openid-configuration), which is mentioned in their documentation linked above as the place to get the ```userinfo_endpoint``` I'm now able to log into ueberauth_example locally, and it displays my full name and profile picture correctly, without having to enable the Google+ API in the Google API Manager.

I'm not totally sure if there are any additional consequences to this change, such as whether certain profile information needs to be parsed out of different fields. According to Google, ```Unless you are using the plus.login scope, these endpoints provide identical information, just formatted differently.```. However, since ueberauth_google already uses ```https://www.googleapis.com/plus/v1/people/me/openIdConnect``` instead of ```https://www.googleapis.com/plus/v1/people/me```, there may not need to be any additional changes (see https://developers.google.com/+/web/api/rest/openidconnect/getOpenIdConnect)

**Comment by doomspork** [comment]
Sounds good to me @jochakovsky 👍

**Comment by doomspork** [comment]
This should be addressed now thanks to @jochakovsky 👍 

I will update (and close) once a new version has been released.
